import customtkinter

child_root=customtkinter.CTk()
# x = self.root.winfo_rootx()
# y = self.root.winfo_rooty()
child_root.geometry(f"350x520")  
child_root.title("Editování optiky: ")
optic_type =                customtkinter.CTkLabel(master = child_root,text = "Typ objektivu:",font=("Arial",22,"bold"))
new_name =                  customtkinter.CTkEntry(master = child_root,font=("Arial",22),width=300,height=50,corner_radius=0)
button_next_st =            customtkinter.CTkButton(master = child_root,text = "Uložit",font=("Arial",22,"bold"),width = 200,height=50,corner_radius=0)
button_prev_st =            customtkinter.CTkButton(master = child_root,text = "Uložit",font=("Arial",22,"bold"),width = 200,height=50,corner_radius=0)
alternative_type =          customtkinter.CTkLabel(master = child_root,text = "Alternativa:",font=("Arial",22,"bold"))
alternative_entry =         customtkinter.CTkOptionMenu(master = child_root,font=("Arial",22),dropdown_font=("Arial",22),width=300,height=50,corner_radius=0)
note_label =                customtkinter.CTkLabel(master = child_root,text = "Poznámky:",font=("Arial",22,"bold"))
notes_input =               customtkinter.CTkTextbox(master = child_root,font=("Arial",22),width=300,height=200)
button_save =               customtkinter.CTkButton(master = child_root,text = "Uložit",font=("Arial",22,"bold"),width = 200,height=50,corner_radius=0,)
button_continue =           customtkinter.CTkButton(master = child_root,text = "Pokračovat",font=("Arial",22,"bold"),width = 200,height=50,corner_radius=0)
optic_type                  .pack(pady=(15,5),padx=10,anchor="w",expand=False,side = "top")
# optic_type_entry            .pack(pady = 5, padx = 10,anchor="w",expand=False,side="top")
new_name                    .pack(pady = 5, padx = 10,anchor="w",expand=False,side="top")
button_next_st              .pack(pady = 5, padx = 10,anchor="w",expand=False,side="left")
button_prev_st              .pack(pady = 5, padx = 10,anchor="w",expand=False,side="left")
alternative_type            .pack(pady = 5, padx = 10,anchor="w",expand=False,side="top")
alternative_entry           .pack(pady = 5, padx = 10,anchor="w",expand=False,side="top")
note_label                  .pack(pady = 5, padx = 10,anchor="w",expand=False,side="top")
notes_input                 .pack(pady = 5, padx = 10,expand=True,side="top")
button_save                 .pack(pady = 5, padx = 10,expand=True,side="left",anchor="w")
button_continue             .pack(pady = 5, padx = 10,expand=True,side="left",anchor="w")


child_root.mainloop()
